on: push

jobs:
  install:
    runs-on: macos-latest
    steps:
      - uses: Homebrew/actions/setup-homebrew@main
      - uses: actions/checkout@v2
      - name: Link perses into Homebrew
        run: ln -nsf $(pwd)/perses.rb $(brew --prefix)/Library/Taps/homebrew/homebrew-core/Formula/p/perses.rb
      - name: Install perses
        env:
          HOMEBREW_NO_AUTO_UPDATE: true
          HOMEBREW_NO_INSTALL_FROM_API: true
        run: brew install --build-from-source --verbose --debug perses
